# Generated by Django 2.2.28 on 2022-05-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartLibrarie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('link', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('library', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to='charts.ChartLibrarie')),
                ('variables', models.ManyToManyField(blank=True, to='pyscada.Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
