# Generated by Django 2.2.28 on 2022-05-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Bar'), (1, 'Line')], default=0)),
                ('library', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to='charts.ChartLibrarie')),
                ('variables', models.ManyToManyField(blank=True, to='pyscada.Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
