# Generated by Django 2.2.28 on 2022-05-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0002_auto_20220516_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='ApexChart',
        ),
    ]
