# Generated by Django 3.2.13 on 2022-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0005_categoriesd3_chartd3'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesd3',
            name='linkType',
            field=models.ManyToManyField(to='pyscada.Variable'),
        ),
    ]
