# Generated by Django 3.2.13 on 2022-05-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0006_categoriesd3_linktype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartD3',
            new_name='D3Chart',
        ),
    ]
