# Generated by Django 3.2.13 on 2022-05-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_rename_categoriesd3_d3category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3chart',
            name='variables',
        ),
    ]
