# Generated by Django 3.2.13 on 2022-05-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0009_remove_d3chart_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3category',
            name='link_type',
        ),
    ]
