# Generated by Django 3.2.13 on 2022-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0010_remove_d3category_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3category',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='d3category',
            name='label',
        ),
        migrations.RemoveField(
            model_name='d3category',
            name='linkType',
        ),
        migrations.RemoveField(
            model_name='d3category',
            name='links',
        ),
        migrations.AddField(
            model_name='d3category',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='d3chart',
            name='base_categories',
            field=models.ManyToManyField(to='charts.D3Category'),
        ),
        migrations.AlterField(
            model_name='d3category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CategoryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.PositiveSmallIntegerField(choices=[(0, 'Variable'), (1, 'Category')], default=2, help_text='Linked variables or categories')),
                ('categories', models.ManyToManyField(to='charts.D3Category')),
                ('variables', models.ManyToManyField(to='pyscada.Variable')),
            ],
        ),
    ]
