# Generated by Django 3.2.13 on 2022-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0013_auto_20220530_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3category',
            name='links',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Variable'), (1, 'Category')], default=2, help_text='Linked variables or categories'),
        ),
        migrations.AddField(
            model_name='d3category',
            name='variables',
            field=models.ManyToManyField(to='pyscada.Variable'),
        ),
        migrations.DeleteModel(
            name='CategoryLink',
        ),
    ]
