# Generated by Django 3.2.13 on 2022-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20220530_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3category',
            name='links',
        ),
    ]
