# Generated by Django 3.2.13 on 2022-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0097_auto_20220118_1046'),
        ('charts', '0015_remove_d3category_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3category',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='_charts_d3category_categories_+', to='charts.D3Category'),
        ),
        migrations.AlterField(
            model_name='d3category',
            name='variables',
            field=models.ManyToManyField(blank=True, to='pyscada.Variable'),
        ),
    ]
