# Generated by Django 3.2.13 on 2022-06-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0017_alter_d3category_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexchart',
            name='x_axis_label',
        ),
        migrations.RemoveField(
            model_name='apexchart',
            name='y_axis_label',
        ),
    ]
