# Generated by Django 3.2.13 on 2022-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0018_auto_20220602_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexchart',
            name='y_axis_label',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
