# Generated by Django 3.2.13 on 2022-06-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0098_alter_device_polling_interval'),
        ('charts', '0019_apexchart_y_axis_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexchart',
            name='y_axis_label',
        ),
        migrations.AlterField(
            model_name='apexchart',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bar'), (1, 'Line'), (2, 'Mixed Bar')], default=0),
        ),
        migrations.CreateModel(
            name='ApexChartAxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=400)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.apexchart')),
                ('variables', models.ManyToManyField(to='pyscada.Variable')),
            ],
            options={
                'verbose_name': 'Y Axis',
                'verbose_name_plural': 'Y Axis',
            },
        ),
    ]
