# Generated by Django 3.2.13 on 2022-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0022_apexchart_stacked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apexmixedchart',
            name='variables',
        ),
        migrations.AddField(
            model_name='apexchartaxis',
            name='lineOrBar',
            field=models.BooleanField(default=False, help_text='Display data as a line or a bar'),
        ),
    ]
